apiVersion: apps/v1
kind: Deployment
metadata:
  name: addition-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: addition-service
  template:
    metadata:
      labels:
        app: addition-service
    spec:
      containers:
      - name: addition-service
        image: gcr.io/ceng489project/addition:latest
        ports:
        - containerPort: 5000