apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplication-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multiplication-service
  template:
    metadata:
      labels:
        app: multiplication-service
    spec:
      containers:
      - name: multiplication-service
        image: gcr.io/ceng489project/multiplication:latest
        ports:
        - containerPort: 5000